"""
Add column for configurable radio station sort order

Revision ID: 000b09a14879
Revises: f72f7ddab339
Create Date: 2023-10-01 17:22:25.346587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000b09a14879'
down_revision: Union[str, None] = 'f72f7ddab339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RadioStations', sa.Column('SortOrder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RadioStations', 'SortOrder')
    # ### end Alembic commands ###
