"""
Split artwork into a separate table

Revision ID: 1abb628b0b5b
Revises: 000b09a14879
Create Date: 2023-11-25 09:31:40.516086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abb628b0b5b'
down_revision: Union[str, None] = '000b09a14879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artwork',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Path', sa.String(), nullable=True),
    sa.Column('Blob', sa.LargeBinary(), nullable=True),
    sa.Column('BlobHash', sa.String(), nullable=True),
    sa.Column('Width', sa.Integer(), nullable=True),
    sa.Column('Height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    with op.batch_alter_table('Tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Artwork', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_artwork", 'Artwork', ['Artwork'], ['Id'])
        batch_op.drop_column('ArtworkHeight')
        batch_op.drop_column('ArtworkPath')
        batch_op.drop_column('ArtworkBlob')
        batch_op.drop_column('ArtworkWidth')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ArtworkWidth', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ArtworkBlob', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('ArtworkPath', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('ArtworkHeight', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Artwork')

    op.drop_table('Artwork')
    # ### end Alembic commands ###
