"""
Add an index to track filepath

Revision ID: 8d53a02d7bb6
Revises: d82c1f9658f7
Create Date: 2025-08-31 11:46:36.030973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d53a02d7bb6'
down_revision: Union[str, None] = 'd82c1f9658f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Tracks_Filepath'), ['Filepath'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Tracks_Filepath'))

    # ### end Alembic commands ###
